### ISSUE TITLE
PokedexShow2 needs adjusting for the dba table

### ISSUE THREAD

**Issue by Rangi42** [aaaaaa123456789/pokecrystal16#2]
This should do `add hl, bc` three times: https://github.com/aaaaaa123456789/pokecrystal16/blob/5d0e92bf8e79e9b77f0a8588a182ada775a57165/engine/pokegear/radio.asm#L708-L717

**Comment by aaaaaa123456789** [comment]
Resolved in last `master` commit by 2020-05-25 update.
